/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package java_quanly;

import Controller.DAO_ChiTietHD;
import Object.ChiTietHoaDon;
import Object.ChiTietMatHang;
import java.util.ArrayList;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Phuong Thang
 */
public class fChiTietHD extends javax.swing.JFrame {

    DefaultTableModel model;
    DefaultTableModel modell;
    ArrayList<ChiTietHoaDon> list = new ArrayList<>();
    ArrayList<ChiTietMatHang> listmh = new ArrayList<>();
    public fChiTietHD() {
        initComponents();
        model = (DefaultTableModel) tableHoaDon.getModel();
        modell = (DefaultTableModel) tableHangNhap.getModel();
        resize();
        switch (fThongKe.comboSelectedIndex) {
            case 0:
                getDataNgay();
                break;
            case 1:
                getDataThang();
                break;
            case 2:
                getDataNam();
                break;
            default:
                break;
        }
    }
    public void getDataNgay()
    {
        model.setNumRows(0);
        list = new DAO_ChiTietHD().getListHoaDonNgay(fThongKe.ngay, fThongKe.thang, fThongKe.nam);
        int i = 1;
        for(ChiTietHoaDon obj:list)
        {
            model.addRow(new Object[]{
            i++, obj.getMahd(),obj.getNgayban(),obj.getNhanvien(),obj.getTienban(),obj.getGiamgia()+" %",obj.getThanhtien()
            });
        }
    }
    public void getDataThang()
    {
        model.setNumRows(0);
        list = new DAO_ChiTietHD().getListHoaDonThang(fThongKe.thang, fThongKe.nam);
        int i = 1;
        for(ChiTietHoaDon obj:list)
        {
            model.addRow(new Object[]{
            i++, obj.getMahd(),obj.getNgayban(),obj.getNhanvien(),obj.getTienban(),obj.getGiamgia()+" %",obj.getThanhtien()
            });
        }
    }
    public void getDataNam()
    {
        model.setNumRows(0);
        list = new DAO_ChiTietHD().getListHoaDonNam(fThongKe.nam);
        int i = 1;
        for(ChiTietHoaDon obj:list)
        {
            model.addRow(new Object[]{
            i++, obj.getMahd(),obj.getNgayban(),obj.getNhanvien(),obj.getTienban(),obj.getGiamgia()+" %",obj.getThanhtien()
            });
        }
    }
    public void getCTHD(String mapn)
    {
        modell.setNumRows(0);
        listmh = new DAO_ChiTietHD().getListChiTietMatHang(mapn);
        int i = 1;
        for(ChiTietMatHang obj:listmh)
        {
            modell.addRow(new Object[]{
            i++, obj.getMamh(),obj.getTenmh(),obj.getSoluong(),obj.getDongia(),String.format("%,.0f",Double.parseDouble(obj.getSoluong())*Double.parseDouble(obj.getDongia())).replace(",", ".")
            });
        }
    }
    public final void resize()
    {
        tableHoaDon.setAutoResizeMode(JTable.AUTO_RESIZE_OFF); 
        tableHoaDon.getColumnModel().getColumn(0).setPreferredWidth(45);
        tableHoaDon.getColumnModel().getColumn(1).setPreferredWidth(120);
        tableHoaDon.getColumnModel().getColumn(2).setPreferredWidth(100);
        tableHoaDon.getColumnModel().getColumn(3).setPreferredWidth(120);
        tableHoaDon.getColumnModel().getColumn(4).setPreferredWidth(80);
        tableHoaDon.getColumnModel().getColumn(5).setPreferredWidth(80);
        tableHoaDon.getColumnModel().getColumn(6).setPreferredWidth(100);
        
        tableHangNhap.setAutoResizeMode(JTable.AUTO_RESIZE_OFF); 
        tableHangNhap.getColumnModel().getColumn(0).setPreferredWidth(45);
        tableHangNhap.getColumnModel().getColumn(1).setPreferredWidth(120);
        tableHangNhap.getColumnModel().getColumn(2).setPreferredWidth(150);
        tableHangNhap.getColumnModel().getColumn(3).setPreferredWidth(100);
        tableHangNhap.getColumnModel().getColumn(4).setPreferredWidth(100);
        tableHangNhap.getColumnModel().getColumn(5).setPreferredWidth(80);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableHangNhap = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableHoaDon = new javax.swing.JTable();
        btnThoat1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(52, 73, 94));

        jPanel2.setBackground(new java.awt.Color(230, 136, 24));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Chi Tiết Hóa Đơn");

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/desura-icon (2).png"))); // NOI18N

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Phương Thắng Store");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/papers (1).png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel21))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jLabel20)))
                .addGap(232, 232, 232)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addContainerGap(492, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel21)))
                .addGap(21, 21, 21))
        );

        tableHangNhap.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã hàng nhập", "Tên hàng nhập", "Số lượng", "Đơn giá", "Thành tiền"
            }
        ));
        jScrollPane1.setViewportView(tableHangNhap);

        tableHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã hóa đơn", "Ngày bán", "Nhân Viên", "Tiền bán", "Giảm giá", "Thành tiền"
            }
        ));
        tableHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableHoaDonMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableHoaDon);

        btnThoat1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnThoat1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/out.png"))); // NOI18N
        btnThoat1.setText("Thoát");
        btnThoat1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoat1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 643, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnThoat1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnThoat1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tableHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableHoaDonMouseClicked
        int id = tableHoaDon.getSelectedRow();
        if(id>=0)
        {
            String mapn = (String) model.getValueAt(id, 1);
            getCTHD(mapn);

        }
    }//GEN-LAST:event_tableHoaDonMouseClicked

    private void btnThoat1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoat1ActionPerformed
        this.setVisible(false);
        fThongKe thongke = new fThongKe();
        thongke.setLocationRelativeTo(null);
        thongke.setVisible(true);
    }//GEN-LAST:event_btnThoat1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fChiTietHD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fChiTietHD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fChiTietHD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fChiTietHD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fChiTietHD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThoat1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tableHangNhap;
    private javax.swing.JTable tableHoaDon;
    // End of variables declaration//GEN-END:variables
}
