/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package java_quanly;

import Controller.DAO_Kho;
import Object.Kho;
import java.awt.event.ItemEvent;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Phuong Thang
 */
public class fKho extends javax.swing.JFrame {

    ArrayList<Kho> list = new ArrayList<>();
    ArrayList<String> listmahn = new ArrayList<>();
    ArrayList<String> listtenhn = new ArrayList<>();
    ArrayList<String> listloai = new ArrayList<>();
    DefaultTableModel model;
    int idcomboboxSelected = 0;
    public fKho() {
        initComponents();
        model = (DefaultTableModel) tableKho.getModel();
        getData();
        cbDoiTuong.setEditable(false);
        CheckEnabled(true);
    }
    public final void getData()
    {
        model.setNumRows(0);
        list = new DAO_Kho().getKhoHang();
        int i = 1;
        for(Kho obj:list)
        {
            model.addRow(new Object[]{
            i++, obj.getMahn(),obj.getTenhn(),obj.getLoai(),obj.getSoluong(),String.format("%,.0f", Double.parseDouble(obj.getDongia())).replace(",", ".")
            });
        }
    }
    public final void getTruyVan(String truyvan)
    {
        model.setNumRows(0);
        list = new DAO_Kho().getTruyVan(truyvan);
        int i = 1;
        for(Kho obj:list)
        {
            model.addRow(new Object[]{
            i++, obj.getMahn(),obj.getTenhn(),obj.getLoai(),obj.getSoluong(),String.format("%,.0f", Double.parseDouble(obj.getDongia())).replace(",", ".")
            });
        }
    }
    public final void getDataTimKiem(String doituong,String truyvan)
    {
        model.setNumRows(0);
        list = new DAO_Kho().TimKiem(doituong,truyvan);
        int i = 1;
        for(Kho obj:list)
        {
            model.addRow(new Object[]{
            i++, obj.getMahn(),obj.getTenhn(),obj.getLoai(),obj.getSoluong(),String.format("%,.0f", Double.parseDouble(obj.getDongia())).replace(",", ".")
            });
        }
    }
    public final void getSapXep(String loai, String chieu)
    {
        model.setNumRows(0);
        int index = 0;
        list = new DAO_Kho().getSapXep(loai, chieu);
        int i = 1;
        for(Kho obj:list)
        {
            model.addRow(new Object[]{
            i++, obj.getMahn(),obj.getTenhn(),obj.getLoai(),obj.getSoluong(),String.format("%,.0f", Double.parseDouble(obj.getDongia())).replace(",", ".")
            });
        }
    }
    public final void getSapXepTimKiem(String truyvan,String loai, String chieu)
    {
        model.setNumRows(0);
        list = new DAO_Kho().TimKiemSapXep(truyvan,loai, chieu);
        int i = 1;
        for(Kho obj:list)
        {
            model.addRow(new Object[]{
            i++, obj.getMahn(),obj.getTenhn(),obj.getLoai(),obj.getSoluong(),String.format("%,.0f", Double.parseDouble(obj.getDongia())).replace(",", ".")
            });
        }
    }
    public final void CheckEnabled(boolean check)
    {
        rdGiam.setEnabled(check);
        rdTang.setEnabled(check);
        cbLuaChon.setEnabled(check);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableKho = new javax.swing.JTable();
        cbTimKiem = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        rdTang = new javax.swing.JRadioButton();
        rdGiam = new javax.swing.JRadioButton();
        btnThoat = new javax.swing.JButton();
        cbDoiTuong = new javax.swing.JComboBox<>();
        cbLuaChon = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtTruyvan = new javax.swing.JTextField();
        btnTimKiem = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kho Hàng");

        jPanel1.setBackground(new java.awt.Color(52, 73, 94));

        jPanel2.setBackground(new java.awt.Color(230, 136, 24));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Kho Hàng");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/container (1).png"))); // NOI18N

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/desura-icon (2).png"))); // NOI18N

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Phương Thắng Store");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel18))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jLabel19)))
                .addGap(273, 273, 273)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(407, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel18)))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        tableKho.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã mặt hàng", "Tên mặt hàng", "Loại", "Số lượng tồn kho", "Đơn giá"
            }
        ));
        jScrollPane1.setViewportView(tableKho);

        cbTimKiem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbTimKiem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tất cả", "Mã mặt hàng", "Tên mặt hàng", "Loại", "Số lượng", "Đơn giá" }));
        cbTimKiem.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbTimKiemItemStateChanged(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Tìm Kiếm :");

        rdTang.setBackground(new java.awt.Color(52, 73, 94));
        buttonGroup1.add(rdTang);
        rdTang.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rdTang.setForeground(new java.awt.Color(255, 255, 255));
        rdTang.setText("Tăng dần");
        rdTang.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rdTangItemStateChanged(evt);
            }
        });

        rdGiam.setBackground(new java.awt.Color(52, 73, 94));
        buttonGroup1.add(rdGiam);
        rdGiam.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rdGiam.setForeground(new java.awt.Color(255, 255, 255));
        rdGiam.setText("Giảm dần");
        rdGiam.setBorder(null);
        rdGiam.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rdGiamItemStateChanged(evt);
            }
        });

        btnThoat.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/out.png"))); // NOI18N
        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        cbDoiTuong.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbDoiTuong.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tất cả" }));
        cbDoiTuong.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbDoiTuongItemStateChanged(evt);
            }
        });

        cbLuaChon.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbLuaChon.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Số lượng", "Đơn giá" }));
        cbLuaChon.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbLuaChonItemStateChanged(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Tìm Kiếm :");

        btnTimKiem.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnTimKiem.setText("Tìm Kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTruyvan, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(cbDoiTuong, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cbLuaChon, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(rdTang)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rdGiam)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnThoat)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(btnTimKiem)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(rdTang)
                    .addComponent(rdGiam)
                    .addComponent(cbTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbDoiTuong, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbLuaChon, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTimKiem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(txtTruyvan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 456, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed

            this.setVisible(false);
            fHeThong hethong = new fHeThong();
            hethong.setLocationRelativeTo(null);
            hethong.setVisible(true);

    }//GEN-LAST:event_btnThoatActionPerformed

    private void cbTimKiemItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbTimKiemItemStateChanged
        if(evt.getStateChange()==ItemEvent.SELECTED)
        {
            int index = cbTimKiem.getSelectedIndex();
            idcomboboxSelected = index;
            if(index == 0)
            {
                cbDoiTuong.setEditable(true);
                cbDoiTuong.removeAllItems();
                cbDoiTuong.addItem("Tất cả");
                CheckEnabled(true);
                
            }
            else if(index==1)
            {
                cbDoiTuong.setEditable(true);
                cbDoiTuong.removeAllItems();
                listmahn = new DAO_Kho().getListMaHN();
                for(String obj:listmahn)
                {
                    cbDoiTuong.addItem(obj);
                }
                CheckEnabled(false);
                
            }
            else if(index==2)
            {
                cbDoiTuong.setEditable(true);
                cbDoiTuong.removeAllItems();
                listtenhn = new DAO_Kho().getListTenHN();
                for(String obj:listtenhn)
                {
                    cbDoiTuong.addItem(obj);
                }
                CheckEnabled(false);
            }
            else if(index==3)
            {
                cbDoiTuong.setEditable(true);
                cbDoiTuong.removeAllItems();
                listloai = new DAO_Kho().getListLoai();
                for(String obj:listloai)
                {
                    cbDoiTuong.addItem(obj);
                }
                CheckEnabled(true);
            }
            else{
                cbDoiTuong.setEditable(true);
                cbDoiTuong.removeAllItems();
                cbDoiTuong.addItem("Tăng dần");
                cbDoiTuong.addItem("Giảm dần");
                CheckEnabled(false);
            }
            
            
        }
    }//GEN-LAST:event_cbTimKiemItemStateChanged

    private void cbDoiTuongItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbDoiTuongItemStateChanged
        if(evt.getStateChange()==ItemEvent.SELECTED)
        {
            String truyvan = cbDoiTuong.getItemAt(cbDoiTuong.getSelectedIndex());
            int id = cbDoiTuong.getSelectedIndex();
            if(idcomboboxSelected == 0)
            {
                getData();
            }
            else if(idcomboboxSelected == 1)
            {
                getDataTimKiem("tbHangNhap.MaHN",truyvan);
            }
            else if(idcomboboxSelected == 2)
            {
                getDataTimKiem("TenHN",truyvan);
            }
            else if(idcomboboxSelected == 3)
            {
                getDataTimKiem("Loai",truyvan);
            }
            else if(idcomboboxSelected == 4)
            {
                if(id == 0)
                {
                    getSapXep("tongsoluong", "asc");
                }
                else if(id == 1)
                {
                    getSapXep("tongsoluong", "desc");
                }
            }
            else if(idcomboboxSelected == 5)
            {
                if(id == 0)
                {
                    getSapXep("Convert(int,tbHangNhap.Dongia)", "asc");
                }
                else if(id == 1)
                {
                    getSapXep("Convert(int,tbHangNhap.Dongia)", "desc");
                }
            }
                
            
            
        }
    }//GEN-LAST:event_cbDoiTuongItemStateChanged

    private void cbLuaChonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbLuaChonItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cbLuaChonItemStateChanged

    private void rdTangItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rdTangItemStateChanged
        if(idcomboboxSelected==0)
        {
            int cbLuachonindex = cbLuaChon.getSelectedIndex();
            if(evt.getStateChange()==ItemEvent.SELECTED)
            {
                if(cbLuachonindex == 0)
                {
                    getSapXep("tongsoluong","asc");
                }
                if(cbLuachonindex ==1)
                {
                 getSapXep("Convert(int,tbHangNhap.Dongia)","asc");
                }
            }
        }
        else
        {
            int cbLuachonindex = cbLuaChon.getSelectedIndex();
            if(evt.getStateChange()==ItemEvent.SELECTED)
            {
                String truyvan = cbDoiTuong.getItemAt(cbDoiTuong.getSelectedIndex());
                if(cbLuachonindex == 0)
                {
                    getSapXepTimKiem(truyvan,"tongsoluong","asc");
                }
                if(cbLuachonindex ==1)
                {
                 getSapXepTimKiem(truyvan,"Convert(int,tbHangNhap.Dongia)","asc");
                }
            }
        }
        
        
    }//GEN-LAST:event_rdTangItemStateChanged

    private void rdGiamItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rdGiamItemStateChanged
        if(idcomboboxSelected == 0)
        {
            int cbLuachonindex = cbLuaChon.getSelectedIndex();
            if(evt.getStateChange()==ItemEvent.SELECTED)
            {
                if(cbLuachonindex == 0)
                {
                    getSapXep("tongsoluong","desc");
                }
                if(cbLuachonindex ==1)
                {
                 getSapXep("Convert(int,tbHangNhap.Dongia)","desc");
                }
            }
        }
        else
        {
            int cbLuachonindex = cbLuaChon.getSelectedIndex();
            if(evt.getStateChange()==ItemEvent.SELECTED)
            {
                String truyvan = cbDoiTuong.getItemAt(cbDoiTuong.getSelectedIndex());
                if(cbLuachonindex == 0)
                {
                    getSapXepTimKiem(truyvan,"tongsoluong","desc");
                }
                if(cbLuachonindex ==1)
                {
                    getSapXepTimKiem(truyvan,"Convert(int,tbHangNhap.Dongia)","desc");
                }
            }
        }
    }//GEN-LAST:event_rdGiamItemStateChanged

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        String truyvan = txtTruyvan.getText();
        getTruyVan(truyvan);
    }//GEN-LAST:event_btnTimKiemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fKho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fKho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fKho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fKho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fKho().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbDoiTuong;
    private javax.swing.JComboBox<String> cbLuaChon;
    private javax.swing.JComboBox<String> cbTimKiem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rdGiam;
    private javax.swing.JRadioButton rdTang;
    private javax.swing.JTable tableKho;
    private javax.swing.JTextField txtTruyvan;
    // End of variables declaration//GEN-END:variables
}
