/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package java_quanly;

import Controller.DAO_ChiTietPN;
import Controller.DAO_HoaDon;
import Controller.DAO_NhapHang;
import Controller.DAO_Thongtinmathang;
import Controller.DAO_Thongtinnhanvien;
import Object.PhieuNhap;
import Object.ThongTinMatHang;
import Object.ThongTinNhanVien;
import java.awt.event.ItemEvent;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.Instant;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Phuong Thang
 */
public class fNhapHang extends javax.swing.JFrame {

    int comboLoaiIndex;
    int comboboxSelected;
    int thanhtien;
    int soluongcu;
    int id;
    ArrayList<ThongTinMatHang> listMatHang = new ArrayList<>();
    ArrayList<ThongTinMatHang> listMatHangLoai = new ArrayList<>();
    ArrayList<ThongTinNhanVien> listInforNhanVien = new ArrayList<>();
    ArrayList<PhieuNhap> list = new ArrayList<>();
    ArrayList<String> loaiMH = new ArrayList<>();
    DefaultTableModel model;
    boolean checked = false;
    public fNhapHang() {
        initComponents();
        model = (DefaultTableModel) tableNhapHang.getModel();
        getCombobox();
        long now = Instant.now().toEpochMilli();
        txtMaPN.setText("PN"+String.valueOf(now));
        getDate();
        Soluong.setValue(1);
        listMatHang = new DAO_Thongtinmathang().getInforMatHang();
        resize();
        txtMaPN.setEditable(false);
        txtTongtien.setEditable(false);
        txtDongia.setEditable(false);
        Soluong.setValue(1);
        btnSua.setEnabled(false);
        btnXoa.setEnabled(false);
        btnLamMoi.setEnabled(false);
        btnLuu.setEnabled(false);
        Enable(false);
    }
    public final void Enable(boolean check)
    {
        cbMaHang.setEnabled(check);
        cbTenMH.setEnabled(check);
        Soluong.setEnabled(check);
        btnThem.setEnabled(check);
        
    }
    public final void getCombobox()
    {
        listInforNhanVien = new DAO_Thongtinnhanvien().getInforNhanVien();
        for(ThongTinNhanVien obj:listInforNhanVien)
        {
            cbNhanVien.addItem(obj.getHoten());
        }
        cbLoaiMH.addItem("Tất cả");
        loaiMH = new DAO_HoaDon().getLoaiMH();
        for(String i:loaiMH)
        {
            cbLoaiMH.addItem(i);
        }
    }
    public final void getDate()
    {
        txtNgayNhap.setEditable(false);
        Date date = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");                                                                                           
        txtNgayNhap.setText(sdf.format(date));
    }
    public void getData()
    {
        model.setNumRows(0);
        String mapn = txtMaPN.getText();
        list = new DAO_NhapHang().getListPhieuNhap(mapn);
        
        int i = 1;
            for(PhieuNhap object:list)
            {
            model.addRow(new Object[]{
            i++, object.getMapn(), object.getNgaynhap(), object.getTennv(), object.getMahn(),object.getTenhn(),object.getSoluong(),object.getDongia(),String.format("%,.0f",Double.parseDouble(object.getSoluong())*Double.parseDouble(object.getDongia())).replace(",", ".")
            });
            }
        
    }
    public final void resize()
    {
        tableNhapHang.setAutoResizeMode(JTable.AUTO_RESIZE_OFF); 
        tableNhapHang.getColumnModel().getColumn(0).setPreferredWidth(45);
        tableNhapHang.getColumnModel().getColumn(1).setPreferredWidth(120);
        tableNhapHang.getColumnModel().getColumn(2).setPreferredWidth(120);
        tableNhapHang.getColumnModel().getColumn(3).setPreferredWidth(140);
        tableNhapHang.getColumnModel().getColumn(4).setPreferredWidth(140);
        tableNhapHang.getColumnModel().getColumn(5).setPreferredWidth(140);
        tableNhapHang.getColumnModel().getColumn(6).setPreferredWidth(120);
        tableNhapHang.getColumnModel().getColumn(7).setPreferredWidth(120);
        tableNhapHang.getColumnModel().getColumn(8).setPreferredWidth(140);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtMaPN = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtNgayNhap = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtTongtien = new javax.swing.JTextField();
        btnTao = new javax.swing.JButton();
        btnThemHoaDon = new javax.swing.JButton();
        cbNhanVien = new javax.swing.JComboBox<>();
        cbLoaiMH = new javax.swing.JComboBox<>();
        cbMaHang = new javax.swing.JComboBox<>();
        cbTenMH = new javax.swing.JComboBox<>();
        Soluong = new javax.swing.JSpinner();
        txtDongia = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btnLamMoi = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableNhapHang = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        btnLuu = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Nhập Hàng");

        jPanel1.setBackground(new java.awt.Color(52, 73, 94));

        jPanel2.setBackground(new java.awt.Color(230, 136, 24));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nhập Hàng");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/truck.png"))); // NOI18N

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Phương Thắng Store");

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/desura-icon (2).png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel19))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel18)))
                .addGap(330, 330, 330)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel18)))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Mã phiếu nhập :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Ngày nhập :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nhân viên :");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Tiền nhập :");

        txtTongtien.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtTongtien.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtTongtien.setText("0");

        btnTao.setBackground(new java.awt.Color(46, 204, 113));
        btnTao.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnTao.setForeground(new java.awt.Color(255, 255, 255));
        btnTao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/add.png"))); // NOI18N
        btnTao.setText("Tạo");
        btnTao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaoActionPerformed(evt);
            }
        });

        btnThemHoaDon.setBackground(new java.awt.Color(34, 166, 179));
        btnThemHoaDon.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnThemHoaDon.setForeground(new java.awt.Color(255, 255, 255));
        btnThemHoaDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/add.png"))); // NOI18N
        btnThemHoaDon.setText("Thêm phiếu nhập");
        btnThemHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemHoaDonActionPerformed(evt);
            }
        });

        cbLoaiMH.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbLoaiMHItemStateChanged(evt);
            }
        });

        cbMaHang.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbMaHangItemStateChanged(evt);
            }
        });

        cbTenMH.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbTenMHItemStateChanged(evt);
            }
        });

        txtDongia.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtDongia.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtDongia.setText("0");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Loại :");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Mã hàng nhập :");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Tên hàng nhập :");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Số lượng :");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Đơn giá :");

        btnLamMoi.setBackground(new java.awt.Color(52, 152, 219));
        btnLamMoi.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnLamMoi.setForeground(new java.awt.Color(255, 255, 255));
        btnLamMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/update.png"))); // NOI18N
        btnLamMoi.setText("Nhập tiếp");
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });

        btnThem.setBackground(new java.awt.Color(46, 204, 113));
        btnThem.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnThem.setForeground(new java.awt.Color(255, 255, 255));
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/add.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setBackground(new java.awt.Color(155, 89, 182));
        btnSua.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSua.setForeground(new java.awt.Color(255, 255, 255));
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/running_process.png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setBackground(new java.awt.Color(231, 76, 60));
        btnXoa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnXoa.setForeground(new java.awt.Color(255, 255, 255));
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/delete.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        tableNhapHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã phiếu nhập", "Ngày nhập", "Nhân viên", "Mã mặt hàng", "Tên mặt hàng", "Số lượng", "Đơn giá", "Thành tiền"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, false, true, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableNhapHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableNhapHangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableNhapHang);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("đồng");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("đồng");

        btnLuu.setBackground(new java.awt.Color(83, 92, 104));
        btnLuu.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnLuu.setForeground(new java.awt.Color(255, 255, 255));
        btnLuu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/diskette_check.png"))); // NOI18N
        btnLuu.setText("Lưu");
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/out.png"))); // NOI18N
        jButton2.setText("Thoát");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnTao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnThemHoaDon))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMaPN))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTongtien)
                            .addComponent(txtNgayNhap)
                            .addComponent(cbNhanVien, 0, 256, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(4, 4, 4)
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Soluong, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDongia)
                            .addComponent(cbTenMH, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbMaHang, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbLoaiMH, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel17))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnLamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(391, 391, 391))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1075, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtMaPN, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtNgayNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(cbNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtTongtien, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnTao, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnThemHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cbLoaiMH, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cbMaHang, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel9))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cbTenMH, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel10))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Soluong, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel11))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtDongia, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel12)
                                .addComponent(jLabel17))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnLamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(btnLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1075, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaoActionPerformed
        PhieuNhap pn = new PhieuNhap();
        pn.setMapn(txtMaPN.getText());
        try {
            pn.setNgaynhap(new SimpleDateFormat("dd/MM/yyyy").parse(txtNgayNhap.getText()));
        } catch (ParseException ex) {
        }
        listInforNhanVien = new DAO_Thongtinnhanvien().getInforNhanVien();
        int index = cbNhanVien.getSelectedIndex();
        ThongTinNhanVien obj = listInforNhanVien.get(index);
        pn.setManv(obj.getManhanvien());
        if( new DAO_NhapHang().addPhieuNhap(pn))
        {
            btnTao.setEnabled(false);
        }
        btnThem.setEnabled(true);
        Enable(true);
    }//GEN-LAST:event_btnTaoActionPerformed

    private void btnThemHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemHoaDonActionPerformed

        fNhapHang nhaphang = new fNhapHang();
        nhaphang.setLocationRelativeTo(null);
        nhaphang.setVisible(true);
    }//GEN-LAST:event_btnThemHoaDonActionPerformed

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        Soluong.setValue(1); 
        btnThem.setEnabled(true);
        btnSua.setEnabled(false);
        btnXoa.setEnabled(false);
        cbMaHang.setEnabled(true);
        cbTenMH.setEnabled(true);
        btnLamMoi.setEnabled(false);
        cbLoaiMH.setEnabled(true);
    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        PhieuNhap pn = new PhieuNhap();
        pn.setMapn(txtMaPN.getText());
        listInforNhanVien = new DAO_Thongtinnhanvien().getInforNhanVien();
        int index = cbNhanVien.getSelectedIndex();
        ThongTinNhanVien obj = listInforNhanVien.get(index);
        pn.setManv(obj.getManhanvien());
        pn.setTennv(cbNhanVien.getItemAt(cbNhanVien.getSelectedIndex()));
        pn.setMahn(cbMaHang.getItemAt(cbMaHang.getSelectedIndex()));
        pn.setTenhn(cbTenMH.getItemAt(cbTenMH.getSelectedIndex()));
        int soluong = Integer.parseInt(Soluong.getValue().toString());
        pn.setSoluong(String.valueOf(soluong));
        try {
            pn.setNgaynhap(new SimpleDateFormat("dd/MM/yyyy").parse(txtNgayNhap.getText()));
        } catch (ParseException ex) {
        }
        int dongia = Integer.parseInt(txtDongia.getText());
        pn.setDongia(txtDongia.getText());
        list.add(pn);
        if(new DAO_NhapHang().addChiTietPN(pn))
        {
        int tiennhap = dongia * soluong;
        thanhtien += tiennhap;
        String text = String.valueOf(thanhtien);
        txtTongtien.setText(text);
        pn.setTiennhap(String.valueOf(tiennhap));
        
        String soluongdaco = new DAO_ChiTietPN().SoluongTon(cbMaHang.getItemAt(cbMaHang.getSelectedIndex()));
        new DAO_ChiTietPN().updateHangNhap(soluongdaco, cbMaHang.getItemAt(cbMaHang.getSelectedIndex()));
        
        getData();
        btnThem.setEnabled(false);
        btnLamMoi.setEnabled(true);
        btnLuu.setEnabled(true);
        
        }
        

    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        PhieuNhap pn = new PhieuNhap();
        pn.setMapn(txtMaPN.getText());
        listInforNhanVien = new DAO_Thongtinnhanvien().getInforNhanVien();
        int index = cbNhanVien.getSelectedIndex();
        ThongTinNhanVien obj = listInforNhanVien.get(index);
        pn.setManv(obj.getManhanvien());
        pn.setTennv(cbNhanVien.getItemAt(cbNhanVien.getSelectedIndex()));
        comboboxSelected = cbMaHang.getSelectedIndex();
        pn.setMahn(cbMaHang.getItemAt(cbMaHang.getSelectedIndex()));
        pn.setTenhn(cbTenMH.getItemAt(cbTenMH.getSelectedIndex()));
        int soluong = Integer.parseInt(Soluong.getValue().toString());
        pn.setSoluong(String.valueOf(soluong));
        try {
            pn.setNgaynhap(new SimpleDateFormat("dd/MM/yyyy").parse(txtNgayNhap.getText()));
        } catch (ParseException ex) {
        }
        int dongia = Integer.parseInt(txtDongia.getText());
        pn.setDongia(txtDongia.getText());
        list.add(pn);
        if(new DAO_NhapHang().updateChiTietPN(pn))
        {
            thanhtien = thanhtien - (soluongcu*dongia);
            int tienban = dongia * soluong;
            thanhtien += tienban;
            String text = String.valueOf(thanhtien);
            txtTongtien.setText(text);
            pn.setTiennhap(String.valueOf(tienban));
            String soluongdaco = new DAO_ChiTietPN().SoluongTon(cbMaHang.getItemAt(cbMaHang.getSelectedIndex()));
            new DAO_ChiTietPN().updateHangNhap(soluongdaco, cbMaHang.getItemAt(cbMaHang.getSelectedIndex()));
            getData();
            btnSua.setEnabled(false);
            btnXoa.setEnabled(false);
            btnThem.setEnabled(false);
            btnLamMoi.setEnabled(true);
            
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        int result = JOptionPane.showConfirmDialog(rootPane, "Bạn có chắc muốn xóa không","Question",JOptionPane.YES_NO_OPTION);
        if(result==JOptionPane.YES_OPTION)
        {
            String mapn = txtMaPN.getText();
            String mahn = cbMaHang.getItemAt(cbMaHang.getSelectedIndex());
            if(new DAO_NhapHang().deleteChiTietPN(mapn, mahn))
            {
                int dongia = Integer.parseInt(txtDongia.getText());
                thanhtien = thanhtien - soluongcu* dongia;
                JOptionPane.showMessageDialog(rootPane, "Xóa thành công !","Thông báo",JOptionPane.INFORMATION_MESSAGE);
                String soluongdaco = new DAO_ChiTietPN().SoluongTon(cbMaHang.getItemAt(cbMaHang.getSelectedIndex()));
                new DAO_ChiTietPN().updateHangNhap(soluongdaco, cbMaHang.getItemAt(cbMaHang.getSelectedIndex()));
                getData();
                Soluong.setValue(1); 
                String text = String.valueOf(thanhtien);
                txtTongtien.setText(text);
                txtTongtien.setText(text);
                btnSua.setEnabled(false);
                btnXoa.setEnabled(false);
                btnThem.setEnabled(false);
                btnLamMoi.setEnabled(true);
                
                
            }
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void cbLoaiMHItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbLoaiMHItemStateChanged
        if(evt.getStateChange()==ItemEvent.SELECTED)
        {
            comboLoaiIndex = cbLoaiMH.getSelectedIndex();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
            if(comboLoaiIndex == 0)
            {
                cbMaHang.removeAllItems();
                cbTenMH.removeAllItems();
                listMatHang = new DAO_Thongtinmathang().getInforMatHang();
                for(ThongTinMatHang obj : listMatHang)
                {
                    cbMaHang.addItem(obj.getMahang());
                    cbTenMH.addItem(obj.getTenhang());
                }
                
            }
            else if(comboLoaiIndex !=0)
            {
                cbMaHang.removeAllItems();
                cbTenMH.removeAllItems();
                String loai = cbLoaiMH.getItemAt(cbLoaiMH.getSelectedIndex());
                listMatHangLoai = new DAO_Thongtinmathang().getInforMatHangLoai(loai);
                for(ThongTinMatHang obj1 : listMatHangLoai)
                {
                    cbMaHang.addItem(obj1.getMahang());
                    cbTenMH.addItem(obj1.getTenhang());
                }
               
            }
        }
    }//GEN-LAST:event_cbLoaiMHItemStateChanged

    private void cbMaHangItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbMaHangItemStateChanged
        if(evt.getStateChange()==ItemEvent.SELECTED)
        {
            if(comboLoaiIndex==0)
            {
                int index = cbMaHang.getSelectedIndex();
                ThongTinMatHang obj = listMatHang.get(index);
                cbTenMH.setSelectedItem(obj.getTenhang());
                txtDongia.setText(obj.getDongia());
                
            }
            else
            {
                int index = cbMaHang.getSelectedIndex();
                ThongTinMatHang obj = listMatHangLoai.get(index);
                cbTenMH.setSelectedItem(obj.getTenhang());
                txtDongia.setText(obj.getDongia());
                
            }
        }
    }//GEN-LAST:event_cbMaHangItemStateChanged

    private void cbTenMHItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbTenMHItemStateChanged
        if(evt.getStateChange()==ItemEvent.SELECTED)
        {
            if(comboLoaiIndex == 0)
            {
                
                int index = cbTenMH.getSelectedIndex();
                ThongTinMatHang obj = listMatHang.get(index);
                cbMaHang.setSelectedItem(obj.getMahang());
                txtDongia.setText(obj.getDongia());
            }
            else
            {
                int index = cbTenMH.getSelectedIndex();
                ThongTinMatHang obj = listMatHangLoai.get(index);
                cbMaHang.setSelectedItem(obj.getMahang());
                txtDongia.setText(obj.getDongia());
                
            }
        }
    }//GEN-LAST:event_cbTenMHItemStateChanged

    private void tableNhapHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableNhapHangMouseClicked
        id = tableNhapHang.getSelectedRow();
        if(id>=0)
        {
            cbLoaiMH.setSelectedIndex(0);
            cbLoaiMH.setEnabled(false);
            cbMaHang.setSelectedItem((String) model.getValueAt(id, 4));
            cbMaHang.setEnabled(false);
            
            
            cbTenMH.setSelectedItem((String) model.getValueAt(id, 5));
            cbTenMH.setEnabled(false);
            txtDongia.setText((String)model.getValueAt(id, 7));
            int value = Integer.parseInt((String) model.getValueAt(id, 6));
            soluongcu = value;
            Soluong.setValue(value);
            btnSua.setEnabled(true);
            btnXoa.setEnabled(true);
            btnThem.setEnabled(false);
            
            
        }
    }//GEN-LAST:event_tableNhapHangMouseClicked

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        if(new DAO_NhapHang().updateTienNhap(txtTongtien.getText(), txtMaPN.getText()))
        {
            checked = true;
            btnLuu.setEnabled(false);
        }
        
    }//GEN-LAST:event_btnLuuActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(checked)
        {
            this.setVisible(false);
            fHeThong hethong = new fHeThong();
            hethong.setLocationRelativeTo(null);
            hethong.setVisible(true);
        }
        else
        {
            int result = JOptionPane.showConfirmDialog(rootPane, "Bạn có chắc muốn thoát không. Mọi thông tin sẽ không được lưu lại","Question",JOptionPane.YES_NO_OPTION);
            if(result==JOptionPane.YES_OPTION)
            {
                String mapn = txtMaPN.getText();
                if(new DAO_NhapHang().deleteCTPN(mapn))
                {
                    if(new DAO_NhapHang().deletePN(mapn))
                    {
                        this.setVisible(false);
                        fHeThong hethong = new fHeThong();
                        hethong.setLocationRelativeTo(null);
                        hethong.setVisible(true);
                    }
                }
                else
                {
                    this.setVisible(false);
                    fHeThong hethong = new fHeThong();
                    hethong.setLocationRelativeTo(null);
                    hethong.setVisible(true);
                }
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fNhapHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fNhapHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fNhapHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fNhapHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fNhapHang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner Soluong;
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnTao;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThemHoaDon;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cbLoaiMH;
    private javax.swing.JComboBox<String> cbMaHang;
    private javax.swing.JComboBox<String> cbNhanVien;
    private javax.swing.JComboBox<String> cbTenMH;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableNhapHang;
    private javax.swing.JTextField txtDongia;
    private javax.swing.JTextField txtMaPN;
    private javax.swing.JTextField txtNgayNhap;
    private javax.swing.JTextField txtTongtien;
    // End of variables declaration//GEN-END:variables
}
